### ISSUE TITLE
Composer install fails

### ISSUE THREAD

**Issue by circlesix** [deity-io/falcon-magento2-module#1]
## Description
The installation of the module with `composer require deity/falcon-magento 1.0.2` fails with error:
>[InvalidArgumentException]                                                                                                                                                        
  Could not find a matching version of package deity/falcon-magento. Check the package spelling, your version constraint and that the package is available in a stability which ma  
  tches your minimum-stability (stable).

I'm running a Magento 2.2.6 installation on a local Docker development env. 

## Expected result
Installation of the Magento 2 module

**Comment by andreasemer** [comment]
Of course this happens, there is no https://packagist.org/?query=deity%2F entry. The maintainers should register there repos there, otherwise you have to add the repo url by hand.

**Comment by sergy-gzh** [comment]
Thank you @andreasemer for pointing that out.
Module is added to packagist.
now you can do `composer require deity/falcon-magento 1.0.2`
