### ISSUE TITLE
Unknown column category.entity_id with Magento 2.2.5 EE

### ISSUE THREAD

**Issue by eliashenrich** [deity-io/falcon-magento2-module#3]
**Describe the bug**
After the module was required into a Magento 2.2.5 EE project, running setup:upgrade will fail with the following message:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category.entity_id' in 'field list'`

**To Reproduce**
1. Create Magento 2.2.5 EE project
2. `composer require deity/falcon-magento 1.0.2`
3. `bin/magento module:enable Deity_MagentoApi`
4. `bin/magento setup:upgrade`

**Expected behavior**
Smooth setup of the Deity/MagentoAPI-module

**Comment by eliashenrich** [comment]
Quick & dirty workaround:

Rename `category.entity_id` to `category.row_id` in file `vendor/deity/falcon-magento/src/Setup/UpgradeData.php`. Then re-run `bin/magento setup:upgrade` and the installation should work fine.

**Comment by sergy-gzh** [comment]
Issue moved to [deity-io/falcon-magento2-development #5](https://github.com/deity-io/falcon-magento2-development/issues/5) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sergy-gzh** [comment]
Issue moved to [deity-io/falcon-magento2-development #6](https://github.com/deity-io/falcon-magento2-development/issues/6) via [**ZenHub**](https://www.zenhub.com/)
