### ISSUE TITLE
Product images are not displayed in Magento 2.2.5. EE

### ISSUE THREAD

**Issue by eliashenrich** [deity-io/falcon-magento2-module#4]
**Describe the bug**
A Magento 2.2.5 EE project with enabled and set up module `Deity_MagentoApi` is accessed through the Falcon demo-client. Products are listed correctly but images are not displayed since they are linked with relative path, e.g. `/7/8/789456123___thumbnail.png`, while the Magento base url is missing. 

**Expected behavior**
Product images being displayed correctly.

**Comment by sergy-gzh** [comment]
Issue moved to [deity-io/falcon-magento2-development #4](https://github.com/deity-io/falcon-magento2-development/issues/4) via [**ZenHub**](https://www.zenhub.com/)
