### ISSUE TITLE
Add "Product URL Suffix" and "Category URL Suffix" to /store/storeConfigs endpoint

### ISSUE THREAD

**Issue by mateuszwozniak** [deity-io/falcon-magento2-module#5]
Following the discussion [under pr #77](https://github.com/deity-io/falcon/pull/77#discussion_r224393109) we need extend `/store/storeViews` endpoint to return 2 additional properties: "Product URL Suffix" and "Category URL Suffix" to correctly handle custom suffixes in Falcon.

**Is your feature request related to a problem? Please describe.**
Falcon adds suffix to product and category paths on its side. We need to know what suffix should be added as currently we use hardcoded `html` suffix.

**Describe the solution you'd like**
Response for `/store/storeConfigs` should contains 2 new properties: `product_url_suffix` and `category_url_suffix`.

**Comment by Borales** [comment]
Just to reference it correctly - deity-io/falcon#77

**Comment by sergy-gzh** [comment]
@mateuszwozniak 
I find `store/storeConfigs` a better fit for this information.
`/store/storeViews` should be used for store-listing components, like store selector or sort of a store list.

**Comment by sergy-gzh** [comment]
Issue moved to [deity-io/falcon-magento2-development #3](https://github.com/deity-io/falcon-magento2-development/issues/3) via [**ZenHub**](https://www.zenhub.com/)
