### ISSUE TITLE
Provide "canonical" URL data for product/category

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon-magento2-module#6]
**Is your feature request related to a problem? Please describe.**
To improve SEO behavior - we need to get "canonical" URL data for Magento entities, so on the front-end side we would provide `<link rel="canonical" href="${canonicalUrl}" />` meta-tag so search-engines would properly parse the page and won't save it as a duplicate content with a different URL.

**Describe the solution you'd like**
Provide `canonicalUrl` property for product and category.

**Comment by sergy-gzh** [comment]
Issue moved to [deity-io/falcon-magento2-development #2](https://github.com/deity-io/falcon-magento2-development/issues/2) via [**ZenHub**](https://www.zenhub.com/)
